import { describe, expect, it } from "vitest";
import type { MemberDirectory } from "@/application/members/contracts";
import type { Sprint } from "@/domain/sprints/sprint";
import type { SprintRepository, SprintTaskDirectory } from "./contracts";
import { SprintReferenceError, SprintService } from "./sprint-service";
const input = { name: "Sprint 18", intendedResult: "Entrega validada", ownerMemberId: "member-1", startsOn: "2026-07-20", endsOn: "2026-07-24", taskIds: ["task-1"] };
function setup({ active = true, tasksExist = true }: { active?: boolean; tasksExist?: boolean } = {}) { let sprint: Sprint | null = null; const repo: SprintRepository = { findById: async () => sprint, create: async (values) => (sprint = { id: "sprint-1", ...values, status: "planned", actualResult: null, learning: null, tasks: values.taskIds.map((taskId) => ({ taskId, taskStatus: "todo", committedAt: "2026-07-20T09:00:00Z", closureDisposition: null })), createdAt: "2026-07-19T09:00:00Z", updatedAt: "2026-07-19T09:00:00Z" }), activate: async (value) => (sprint = { ...value, status: "active" }), cancel: async (value) => (sprint = { ...value, status: "cancelled" }), addTasks: async (value, ids) => (sprint = { ...value, tasks: [...value.tasks, ...ids.map((taskId) => ({ taskId, taskStatus: "todo" as const, committedAt: "2026-07-21T09:00:00Z", closureDisposition: null }))] }), removeTask: async (value, id) => (sprint = { ...value, tasks: value.tasks.filter((task) => task.taskId !== id) }), close: async (value, actualResult, learning, dispositions) => (sprint = { ...value, status: "closed", actualResult, learning, tasks: value.tasks.map((task) => ({ ...task, closureDisposition: dispositions[task.taskId] })) }) }; const members: MemberDirectory = { listActive: async () => [], isActive: async () => active }; const tasks: SprintTaskDirectory = { listTasks: async () => [], tasksExist: async () => tasksExist }; return { service: new SprintService(repo, members, tasks) }; }
describe("SprintService", () => {
  it("cria, ativa, inclui urgência e encerra sem alterar Tasks", async () => { const { service } = setup(); const created = await service.createSprint(input); const active = await service.activateSprint(created.id); await service.addTasks(active.id, ["task-2"]); const closed = await service.closeSprint(active.id, { actualResult: "Resultado", learning: "Aprendizagem", incompleteDispositions: { "task-1": "returned_to_future", "task-2": "split" } }); expect(closed.status).toBe("closed"); expect(closed.tasks.map((task) => task.taskId)).toEqual(["task-1", "task-2"]); });
  it("permite remover compromisso apenas enquanto planeada", async () => { const { service } = setup(); const sprint = await service.createSprint(input); expect((await service.removeTask(sprint.id, "task-1")).tasks).toHaveLength(0); });
  it("rejeita owner inativo e Task inexistente", async () => { await expect(setup({ active: false }).service.createSprint(input)).rejects.toBeInstanceOf(SprintReferenceError); await expect(setup({ tasksExist: false }).service.createSprint(input)).rejects.toBeInstanceOf(SprintReferenceError); });
});
