/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSobreRouteImport } from './routes/_app/sobre'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppPersonalRouteImport } from './routes/_app/personal'
import { Route as AppPassosRouteImport } from './routes/_app/passos'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppHojeRouteImport } from './routes/_app/hoje'
import { Route as AppFoundationsRouteImport } from './routes/_app/foundations'
import { Route as AppFinancasRouteImport } from './routes/_app/financas'
import { Route as AppEngineersRouteImport } from './routes/_app/engineers'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as ApiPublicDbSnapshotRouteImport } from './routes/api/public/db-snapshot'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSobreRoute = AppSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalRoute = AppPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppRoute,
} as any)
const AppPassosRoute = AppPassosRouteImport.update({
  id: '/passos',
  path: '/passos',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHojeRoute = AppHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AppRoute,
} as any)
const AppFoundationsRoute = AppFoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancasRoute = AppFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineersRoute = AppEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicDbSnapshotRoute = ApiPublicDbSnapshotRouteImport.update({
  id: '/api/public/db-snapshot',
  path: '/api/public/db-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/calendario': typeof AppCalendarioRoute
  '/engineers': typeof AppEngineersRoute
  '/financas': typeof AppFinancasRoute
  '/foundations': typeof AppFoundationsRoute
  '/hoje': typeof AppHojeRoute
  '/home': typeof AppHomeRoute
  '/passos': typeof AppPassosRoute
  '/personal': typeof AppPersonalRoute
  '/pipeline': typeof AppPipelineRoute
  '/sobre': typeof AppSobreRoute
  '/api/public/db-snapshot': typeof ApiPublicDbSnapshotRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/calendario': typeof AppCalendarioRoute
  '/engineers': typeof AppEngineersRoute
  '/financas': typeof AppFinancasRoute
  '/foundations': typeof AppFoundationsRoute
  '/hoje': typeof AppHojeRoute
  '/home': typeof AppHomeRoute
  '/passos': typeof AppPassosRoute
  '/personal': typeof AppPersonalRoute
  '/pipeline': typeof AppPipelineRoute
  '/sobre': typeof AppSobreRoute
  '/': typeof AppIndexRoute
  '/api/public/db-snapshot': typeof ApiPublicDbSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/engineers': typeof AppEngineersRoute
  '/_app/financas': typeof AppFinancasRoute
  '/_app/foundations': typeof AppFoundationsRoute
  '/_app/hoje': typeof AppHojeRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/passos': typeof AppPassosRoute
  '/_app/personal': typeof AppPersonalRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/sobre': typeof AppSobreRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/db-snapshot': typeof ApiPublicDbSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/board'
    | '/calendario'
    | '/engineers'
    | '/financas'
    | '/foundations'
    | '/hoje'
    | '/home'
    | '/passos'
    | '/personal'
    | '/pipeline'
    | '/sobre'
    | '/api/public/db-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/board'
    | '/calendario'
    | '/engineers'
    | '/financas'
    | '/foundations'
    | '/hoje'
    | '/home'
    | '/passos'
    | '/personal'
    | '/pipeline'
    | '/sobre'
    | '/'
    | '/api/public/db-snapshot'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/board'
    | '/_app/calendario'
    | '/_app/engineers'
    | '/_app/financas'
    | '/_app/foundations'
    | '/_app/hoje'
    | '/_app/home'
    | '/_app/passos'
    | '/_app/personal'
    | '/_app/pipeline'
    | '/_app/sobre'
    | '/_app/'
    | '/api/public/db-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicDbSnapshotRoute: typeof ApiPublicDbSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sobre': {
      id: '/_app/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AppSobreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal': {
      id: '/_app/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AppPersonalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/passos': {
      id: '/_app/passos'
      path: '/passos'
      fullPath: '/passos'
      preLoaderRoute: typeof AppPassosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hoje': {
      id: '/_app/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AppHojeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foundations': {
      id: '/_app/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof AppFoundationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financas': {
      id: '/_app/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof AppFinancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engineers': {
      id: '/_app/engineers'
      path: '/engineers'
      fullPath: '/engineers'
      preLoaderRoute: typeof AppEngineersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/db-snapshot': {
      id: '/api/public/db-snapshot'
      path: '/api/public/db-snapshot'
      fullPath: '/api/public/db-snapshot'
      preLoaderRoute: typeof ApiPublicDbSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppEngineersRoute: typeof AppEngineersRoute
  AppFinancasRoute: typeof AppFinancasRoute
  AppFoundationsRoute: typeof AppFoundationsRoute
  AppHojeRoute: typeof AppHojeRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPassosRoute: typeof AppPassosRoute
  AppPersonalRoute: typeof AppPersonalRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSobreRoute: typeof AppSobreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppEngineersRoute: AppEngineersRoute,
  AppFinancasRoute: AppFinancasRoute,
  AppFoundationsRoute: AppFoundationsRoute,
  AppHojeRoute: AppHojeRoute,
  AppHomeRoute: AppHomeRoute,
  AppPassosRoute: AppPassosRoute,
  AppPersonalRoute: AppPersonalRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSobreRoute: AppSobreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicDbSnapshotRoute: ApiPublicDbSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
